Address compile error due to removed QMutex ctor
qlowenergycontroller_win.cpp:63:40: error: 'NonRecursive' is not a member of 'QMutex'
     static QMutex controllersGuard(QMutex::NonRecursive);
                                            ^~~~~~~~~~~~

Change-Id: I7bf493fa8853544b0e6eda115e54df06450c8a78
Reviewed-by: Karsten Heimrich <karsten.heimrich@qt.io>