Fix clang-cl errors about narrowing conversions
Force value to be a DWORD (unsigned long) instead of HRESULT (signed long).

Fixes

bluetoothsocket_winrt.cpp(770,10): error: case value evaluates to
      2147952460, which cannot be narrowed to type 'long' [-Wc++11-narrowing]

Change-Id: I4f1eb75807d4783b835094ad1b33e56f601ffb39
Reviewed-by: Alex Blasche <alexander.blasche@qt.io>
Reviewed-by: Oliver Wolff <oliver.wolff@qt.io>