Fix bluez config test failure on clang
This compile failure used to be a warning only but these days is a failure
for clang:

> /home/ablasche/dev/qt/qt512/qtconnectivity/config.tests/bluez/main.cpp:36:11: error: taking the address of a temporary object of type 'bdaddr_t' [-Waddress-of-temporary]
>     bacmp(BDADDR_ANY, BDADDR_LOCAL);
>           ^~~~~~~~~~
> /usr/include/bluetooth/bluetooth.h:310:23: note: expanded from macro 'BDADDR_ANY'
> #define BDADDR_ANY   (&(bdaddr_t) {{0, 0, 0, 0, 0, 0}})
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/ablasche/dev/qt/qt512/qtconnectivity/config.tests/bluez/main.cpp:36:23: error: taking the address of a temporary object of type 'bdaddr_t' [-Waddress-of-temporary]
>     bacmp(BDADDR_ANY, BDADDR_LOCAL);
>                       ^~~~~~~~~~~~
> /usr/include/bluetooth/bluetooth.h:312:23: note: expanded from macro 'BDADDR_LOCAL'
> #define BDADDR_LOCAL (&(bdaddr_t) {{0, 0, 0, 0xff, 0xff, 0xff}})
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2 errors generated.

The need for BDADDR_NONE is obsolete now since the test does not rely on
those defines anymore. The main purpose is to check that bluetooth.h
is available which is already tested by using bacmp and bdaddr_t.

Change-Id: I09da4dc5cd3945ffae7819628b45477a52789006
Reviewed-by: Oliver Wolff <oliver.wolff@qt.io>
Reviewed-by: Kai Koehne <kai.koehne@qt.io>