Fix namespace build
Namespace build of QtConnectivity was broken and failed with
error: conversion from
‘TestNamespace::QBluetoothServiceDiscoveryAgent::Error’ to
‘TestNamespace::QChar’ is ambiguous.
This patch fixes it and at the same time creates nicer output, as
the name instead of the numerical value of the enum item is printed.

Change-Id: Id31d17235a606dc759addfd27d1bf0af3372b643
Reviewed-by: Joerg Bornemann <joerg.bornemann@qt.io>